# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alb's world
email: albert.silvans@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Albert Šilvans is a writer from Riga, Latvia, currently in the first year of his Pure Mathematics Bachelor degree at the University of Groningen, Netherlands. He likes to take long walks in the woods, and occupy quiet park benches. He writes about whatever comes to mind, and hopes to see more of his work published in the future. Albert also programs a little.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: albbalbbbalb
github_username:  albbalbbbalb
instagram1_username: albbalbbbalb
instagram2_username: __init__self


# Build settings
markdown: kramdown
